name: site_webdev

homepage: https://angulardart.xyz

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  dart_style: ^2.2.0
  git: ^2.0.0
  http: ^0.13.3
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.1.5
  code_excerpt_updater:
    path: site-shared/packages/code_excerpt_updater
  code_excerpter:
    path: site-shared/packages/code_excerpter
  grinder: ^0.9.0
  linkcheck: ^2.0.0+1
  shelf_static: ^1.0.0
  shelf: ^1.1.4
