name: angular_tour_of_heroes
description: Tour of Heroes
version: 0.0.1

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  angular: ^7.0.2
  angular_forms: ^4.0.1
  angular_router: ^3.0.1

dev_dependencies:
  angular_test: ^4.0.1
  build_runner: ^2.1.8
  build_test: ^2.1.5
  build_web_compilers: ^3.2.2
  mockito: ^5.1.0
  ngpageloader: ^4.1.0
  test: ^1.6.0
