name: lifecycle_hooks
description: Lifecycle Hooks
version: 0.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  angular: ^7.0.2
  angular_forms: ^4.0.1

dev_dependencies:
  build_runner: ^2.1.8
  build_test: ^2.1.5
  build_web_compilers: ^3.2.2
